<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-SRI8GR7" ignored="0" name="Samsung M31" tests="2" failures="1" timestamp="2023-05-29T02:38:48 IST" time="160.557" errors="0">
  <testcase name="VerifyProductPurchase" time="57.51" classname="tests.GeneralStoreTest"/>
  <testcase name="VerifyProductPurchaseFailing" time="30.652" classname="tests.GeneralStoreTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at testutils.Assertion.assertEquals(Assertion.java:22)
at pages.ProductPage.verifyCartItemCount(ProductPage.java:58)
at tests.GeneralStoreTest.VerifyProductPurchaseFailing(GeneralStoreTest.java:126)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- VerifyProductPurchaseFailing -->
</testsuite> <!-- Samsung M31 -->
